### ISSUE TITLE
Strange results running the ACL2019 irregularity example code

### ISSUE THREAD

**Issue by kmccurdy** [shijie-wu/neural-transducer#1]
hi! I've been playing around with the repo, the code is very nicely organized. but I have a question: I've run the code in `example/irregularity-acl19` exactly as shown in the README, and I'm confused by the numbers I'm getting. I ran it on the English UniMorph data following the README, and also on German UniMorph as I'm working with German right now.

according to the README, the output (i.e. in `model/unimorph/large/monotag-hmm/{lang}-{fold}.decode.{split}.tsv`) contains `p(inflected form|lemma, tags) / len(inflected form)`. I assume this is in the `loss` column in the TSVs, as that's the only column that makes sense.

here's the distribution of values I get in that column. N is number of predicted forms overall, across all folds and dev/test splits, and N(p > 1) is the number of predicted forms where the listed value for `p(inflected form|lemma, tags) / len(inflected form)` > 1. the results are split by whether the model correctly predicted the target form.

| Lang | Prediction correct? | N | N (p > 1) | mean(p) | min(p) | max(p) |
| --- | --- | --- | --- | --- | --- | --- | 
| ENG | Yes | 95861 | 0 | 0.0023 | 1e7 | 0.2833 |
| | No | 5437 | 1524 |  0.9874 | 5e2 | 22.3135 |
| DEU | Yes | 318311 | 0 | 0.0027 | 1e7 | 0.2891 |
| | No | 28423 | 7770 | 0.8299 | 5e2 | 23.2277 |

the main thing that confuses me is that the model systematically assigns *higher* probabilities to forms it gets wrong. (it also looks like there might a bug somewhere if 28% of the incorrectly predicted forms in each language are assigned a probability greater than one.)

going by the paper, the degree of irregularity metric *i* should be calculated as `-log(p / (1 - p))`. applying that to the results above, the average *i* for words the model got *right* is 9.6 (ENG) and 11.0 (DEU), while for words it predicted *wrong* ( excluding forms with `p > 1` where *i* is undefined), the average *i* is 0.7 (ENG, DEU).

this seems completely at odds from the analysis described in the paper. I'm wondering if I've misunderstood something, or ran the example wrong? any ideas what's going on here?

**Comment by shijie-wu** [comment]
Hey @kmccurdy,

The `loss` column is actually probability in log space `-log( p(inflected form|lemma, tags) ) / (len(inflected form) + 1)`. The plus one include a special end-of-sequence token `</s>`. I updated the README to describe it more accurately. Thanks for spotting this error!

Feel free to let me know if you have any more questions.
