### ISSUE TITLE
Writing out final dev/test predictions to file?

### ISSUE THREAD

**Issue by slowwavesleep** [shijie-wu/neural-transducer#13]
Hi,

I want to analyse the actual predictions of a trained model (i.e., the word forms themselves), so I need to save them to a file somehow. Is there an easy way to do that? Sorry, if it's something obvious, but I can't find it at a glance.

**Comment by shijie-wu** [comment]
By default the model will dump the prediction of dev/test set into files `*.decode` https://github.com/shijie-wu/neural-transducer/blob/f33a0520d331efaca4985e83468f35cec0a012cf/src/trainer.py#L324

OTOH, you could also run `src/test.py` with the same arguments but replacing dev/test set, and it will call the same function to produce `*.decode`

**Comment by slowwavesleep** [comment]
Ah, I see now! Predictions are saved along with model checkpoints in the corresponding folder. Thanks!
